development: &development
  :url: redis://localhost:6379
  :host: localhost
  :port: 6379
  :timeout: 1
  :inline: true
test: *development
production: &production
  :url: redis://redistogo:4c318a7e6636264eaec2854f01307538@barb.redistogo.com:10071/
  :host: barb.redistogo.com
  :port: 10071
  :password: 4c318a7e6636264eaec2854f01307538
  :inline: true
  :timeout: 1