development: &development
  :url: ENV["REDIS_LOCAL_URL"]
  :host: localhost
  :port: ENV["REDIS_LOCAL_PORT"]
  :timeout: 1
  :inline: true
test: *development
production: &production
  :url: ENV["REDIS_URL"]
  :host: ENV["REDIS_HOST"]
  :port: ENV["REDIS_PORT"]
  :password: ENV["REDIS_PWD"]
  :inline: true
  :timeout: 1