development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:4c318a7e6636264eaec2854f01307538@barb.redistogo.com:10071/
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: convey_production
